"""Extract PixelMplus10 numeric glyphs into a fixed 8 px 1-bit cell.

PixelMplus10 is built from the bundled M+ 10 px BDF. The required glyph pixels
occupy seven rows; this generator removes only the source cell's empty padding
and keeps every original bitmap pixel unchanged inside an eight-row UI cell.
"""

from __future__ import annotations

import json
from pathlib import Path


PIXEL_SIZE = 8
GLYPH_TEXT = "0123456789ABCDEFabcdefxX.+-"

ROOT = Path(__file__).resolve().parents[1]
BDF_PATH = ROOT / "font-source" / "pixel-mplus" / "mplus_j10r-iso-W5.bdf"
JSON_OUTPUT = ROOT / "font" / "pixel-mplus-10-numeric-8.json"
JS_OUTPUT = ROOT / "font" / "pixel-mplus-10-numeric-8.js"
CPP_OUTPUT = ROOT.parent / "CTRPluginFramework-BlankTemplate-0.8.0" / "Sources" / "PixelMplus10Numeric8.cpp"
GUI_TEST_CPP_OUTPUT = ROOT.parent / "CTRPF-GUI-Test" / "Sources" / "PixelMplus10Numeric8.cpp"


def bdf_row_to_lsb_bits(hex_row: str, width: int) -> int:
    source = int(hex_row, 16)
    source_width = len(hex_row) * 4
    result = 0
    for x in range(width):
        if source & (1 << (source_width - 1 - x)):
            result |= 1 << x
    return result


def parse_bdf(path: Path) -> dict[int, dict]:
    all_glyphs = {}
    current = None
    in_bitmap = False
    for raw_line in path.read_text(encoding="ascii").splitlines():
        line = raw_line.strip()
        if line.startswith("STARTCHAR "):
            current = {"encoding": None, "advance": None, "bbx": None, "bitmap": []}
            in_bitmap = False
        elif current is not None and line == "ENDCHAR":
            encoding = current["encoding"]
            if encoding not in {ord(character) for character in GLYPH_TEXT}:
                current = None
                in_bitmap = False
                continue
            width, height, offset_x, _ = current["bbx"]
            rows = [bdf_row_to_lsb_bits(row, width) for row in current["bitmap"]]
            if height != 11 or len(rows) != 11:
                raise ValueError(f"Unexpected PixelMplus10 source cell height for U+{encoding:04X}")
            removed_padding = rows[:2] + rows[10:]
            if any(removed_padding):
                raise ValueError(f"8px cell crop would remove pixels from U+{encoding:04X}")
            all_glyphs[encoding] = {
                "character": chr(encoding),
                "codepoint": encoding,
                "width": width,
                "height": 8,
                "offsetX": offset_x,
                "offsetY": 0,
                "advance": current["advance"],
                "rows": rows[2:10],
                "source": "PixelMplus10-source-BDF-8px-cell",
            }
            current = None
            in_bitmap = False
        elif current is not None and line == "BITMAP":
            in_bitmap = True
        elif current is not None and in_bitmap:
            current["bitmap"].append(line)
        elif current is not None and line.startswith("ENCODING "):
            current["encoding"] = int(line.split()[1])
        elif current is not None and line.startswith("DWIDTH "):
            current["advance"] = int(line.split()[1])
        elif current is not None and line.startswith("BBX "):
            current["bbx"] = tuple(map(int, line.split()[1:5]))
    return all_glyphs


def build_payload(all_glyphs: dict[int, dict]) -> tuple[dict, list[dict]]:
    missing = [character for character in GLYPH_TEXT if ord(character) not in all_glyphs]
    if missing:
        raise ValueError(f"PixelMplus10 source BDF is missing: {''.join(missing)}")
    glyphs = [all_glyphs[ord(character)] for character in GLYPH_TEXT]
    return {
        "family": "PixelMplus10",
        "style": "Regular",
        "source": "font-source/pixel-mplus/mplus_j10r-iso-W5.bdf",
        "pixelSize": PIXEL_SIZE,
        "sourceDesignPixelSize": 10,
        "ascent": 8,
        "descent": 0,
        "lineHeight": 8,
        "rasterization": "Direct source BDF pixels; empty cell padding cropped; no scaling",
        "glyphCount": len(glyphs),
        "usage": "numeric-values-only",
        "glyphs": {str(glyph["codepoint"]): glyph for glyph in glyphs},
    }, glyphs


def write_web_assets(payload: dict) -> None:
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    JSON_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUTPUT.write_text(serialized, encoding="utf-8")
    JS_OUTPUT.write_text(f"window.PIXEL_MPLUS_10_NUMERIC_8={serialized};\n", encoding="utf-8")


def cpp_character_comment(character: str) -> str:
    return character if character.isalnum() or character in ".+-" else f"U+{ord(character):04X}"


def write_cpp(payload: dict, glyphs: list[dict]) -> None:
    maximum_rows = max(glyph["height"] for glyph in glyphs)
    lines = [
        "// Generated by CTRPF-GUI-Simulator/tools/extract_pixel_mplus_10_numeric_8.py.",
        "// Source: PixelMplus10 M+ 10 px BDF; unchanged pixels in an 8 px cell.",
        '#include "PixelMplus10Numeric8.hpp"',
        "",
        "#include <CTRPluginFramework.hpp>",
        "",
        "namespace CTRPluginFramework",
        "{",
        "    namespace PixelMplus10Numeric8",
        "    {",
        "        namespace",
        "        {",
        "            struct Glyph",
        "            {",
        "                u32 codepoint;",
        "                u8  width;",
        "                u8  height;",
        "                s8  offsetX;",
        "                s8  offsetY;",
        "                u8  advance;",
        f"                u16 rows[{maximum_rows}];",
        "            };",
        "",
        "            static const Glyph kGlyphs[] =",
        "            {",
    ]
    for glyph in glyphs:
        rows = glyph["rows"] + [0] * (maximum_rows - len(glyph["rows"]))
        rows_text = ", ".join(f"0x{row:04X}" for row in rows)
        lines.append(
            "                {"
            f"0x{glyph['codepoint']:04X}, {glyph['width']}, {glyph['height']}, "
            f"{glyph['offsetX']}, {glyph['offsetY']}, {glyph['advance']}, "
            f"{{{rows_text}}}}}, // {cpp_character_comment(glyph['character'])}"
        )
    lines.extend(
        [
            "            };",
            "",
            "            static const Glyph *FindGlyph(u32 codepoint)",
            "            {",
            "                const u32 count = sizeof(kGlyphs) / sizeof(kGlyphs[0]);",
            "                for (u32 index = 0; index < count; ++index)",
            "                    if (kGlyphs[index].codepoint == codepoint)",
            "                        return &kGlyphs[index];",
            "                return nullptr;",
            "            }",
            "        }",
            "",
            f"        int LineHeight(void) {{ return {payload['lineHeight']}; }}",
            "",
            "        int Measure(const std::string &text)",
            "        {",
            "            int width = 0;",
            "            for (u32 index = 0; index < text.size(); ++index)",
            "            {",
            "                const Glyph *glyph = FindGlyph(static_cast<u8>(text[index]));",
            "                width += glyph ? glyph->advance : 4;",
            "            }",
            "            return width;",
            "        }",
            "",
            "        void Draw(const Screen &screen, const std::string &text, int x, int y, const Color &color)",
            "        {",
            "            int cursor = x;",
            "            for (u32 index = 0; index < text.size(); ++index)",
            "            {",
            "                const Glyph *glyph = FindGlyph(static_cast<u8>(text[index]));",
            "                if (glyph == nullptr)",
            "                {",
            "                    cursor += 4;",
            "                    continue;",
            "                }",
            "                for (u32 row = 0; row < glyph->height; ++row)",
            "                {",
            "                    const u16 bits = glyph->rows[row];",
            "                    for (u32 column = 0; column < glyph->width; ++column)",
            "                        if (bits & (1U << column))",
            "                        {",
            "                            const int pixelX = cursor + glyph->offsetX + column;",
            "                            const int pixelY = y + glyph->offsetY + row;",
            "                            const int screenWidth = screen.IsTop ? 400 : 320;",
            "                            if (pixelX >= 0 && pixelX < screenWidth && pixelY >= 0 && pixelY < 240)",
            "                                screen.DrawPixel(pixelX, pixelY, color);",
            "                        }",
            "                }",
            "                cursor += glyph->advance;",
            "            }",
            "        }",
            "    }",
            "}",
            "",
        ]
    )
    generated = "\n".join(lines)
    CPP_OUTPUT.write_text(generated, encoding="utf-8")
    GUI_TEST_CPP_OUTPUT.write_text(generated, encoding="utf-8")


def main() -> None:
    if not BDF_PATH.exists():
        raise SystemExit(f"PixelMplus10 source BDF was not found: {BDF_PATH}")
    payload, glyphs = build_payload(parse_bdf(BDF_PATH))
    write_web_assets(payload)
    write_cpp(payload, glyphs)
    print(f"Extracted {len(glyphs)} numeric glyphs at {PIXEL_SIZE}px")
    print(f"Metrics: ascent={payload['ascent']} descent={payload['descent']} line={payload['lineHeight']}")
    print(f"JSON: {JSON_OUTPUT}")
    print(f"JS:   {JS_OUTPUT}")
    print(f"C++:  {CPP_OUTPUT}")
    print(f"C++:  {GUI_TEST_CPP_OUTPUT}")


if __name__ == "__main__":
    main()
